/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package hcl

import (
	"bytes"
	"fmt"
	"text/template"

	nomadv1alpha1 "github.com/hashicorp/nomad-enterprise-operator/api/v1alpha1"
)

// Generator creates Nomad HCL configuration
type Generator struct {
	cluster          *nomadv1alpha1.NomadCluster
	advertiseAddress string
	gossipKey        string
}

// NewGenerator creates a new HCL generator
func NewGenerator(cluster *nomadv1alpha1.NomadCluster, advertiseAddress, gossipKey string) *Generator {
	return &Generator{
		cluster:          cluster,
		advertiseAddress: advertiseAddress,
		gossipKey:        gossipKey,
	}
}

// Generate produces the server.hcl configuration
func (g *Generator) Generate() (string, error) {
	funcMap := template.FuncMap{
		"intRange": func(n int32) []int {
			result := make([]int, n)
			for i := range result {
				result[i] = i
			}
			return result
		},
	}

	tmpl, err := template.New("server.hcl").Funcs(funcMap).Parse(serverHCLTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse HCL template: %w", err)
	}

	data := g.buildTemplateData()

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute HCL template: %w", err)
	}

	return buf.String(), nil
}

type templateData struct {
	Region                 string
	Datacenter             string
	AdvertiseAddress       string
	Replicas               int32
	ClusterName            string
	Namespace              string
	HeadlessService        string
	GossipKey              string
	ACLEnabled             bool
	TLSEnabled             bool
	TLSCAFile              string
	TLSCertFile            string
	TLSKeyFile             string
	VerifyServerHostname   bool
	VerifyHTTPSClient      bool
	AuditEnabled           bool
	AuditDeliveryGuarantee string
	AuditFormat            string
	AuditRotateDur         string
	AuditRotateMax         int
	Autopilot              autopilotData
}

type autopilotData struct {
	CleanupDeadServers      bool
	LastContactThreshold    string
	MaxTrailingLogs         int
	ServerStabilizationTime string
}

func (g *Generator) buildTemplateData() templateData {
	cluster := g.cluster

	// Defaults
	region := cluster.Spec.Topology.Region
	if region == "" {
		region = "global"
	}

	datacenter := cluster.Spec.Topology.Datacenter
	if datacenter == "" {
		datacenter = cluster.Namespace
	}

	replicas := cluster.Spec.Replicas
	if replicas == 0 {
		replicas = 3
	}

	return templateData{
		Region:               region,
		Datacenter:           datacenter,
		AdvertiseAddress:     g.advertiseAddress,
		Replicas:             replicas,
		ClusterName:          cluster.Name,
		Namespace:            cluster.Namespace,
		HeadlessService:      cluster.Name + "-headless",
		GossipKey:            g.gossipKey,
		ACLEnabled:           cluster.Spec.Server.ACL.Enabled,
		TLSEnabled:           true,
		TLSCAFile:            "/nomad/tls/ca.crt",
		TLSCertFile:          "/nomad/tls/tls.crt",
		TLSKeyFile:           "/nomad/tls/tls.key",
		VerifyServerHostname: true,
		VerifyHTTPSClient:    false,
		AuditEnabled:         cluster.Spec.Server.Audit.Enabled,
		// Audit shape is operator-owned per ADR 0003 ("Fields dropped
		// in v1"): enforced delivery (best-effort is a footgun), JSON
		// only, 24h rotation × 15 files (~15 days). Users needing
		// different log shipping use a sidecar, not rotation tuning.
		AuditDeliveryGuarantee: "enforced",
		AuditFormat:            "json",
		AuditRotateDur:         "24h",
		AuditRotateMax:         15,
		// Autopilot is operator-owned per ADR 0003: cleanup_dead_servers
		// must stay true for Serf cleanup delegation (AC-2.3.4e); the
		// thresholds are Nomad's own defaults.
		Autopilot: autopilotData{
			CleanupDeadServers:      true,
			LastContactThreshold:    "200ms",
			MaxTrailingLogs:         250,
			ServerStabilizationTime: "10s",
		},
	}
}

const serverHCLTemplate = `# Nomad Server Configuration
# Generated by nomad-enterprise-operator

# Data directory
data_dir = "/nomad/data"

# Topology
region     = "{{ .Region }}"
datacenter = "{{ .Datacenter }}"

# Bind address
bind_addr = "0.0.0.0"

# Advertise addresses
advertise {
  http = "{{ .AdvertiseAddress }}:4646"
  rpc  = "{{ .AdvertiseAddress }}:4647"
  serf = "{{ "{{ GetPrivateIP }}" }}:4648"
}

# Ports
ports {
  http = 4646
  rpc  = 4647
  serf = 4648
}

# Server configuration
server {
  enabled = true
  bootstrap_expect = {{ .Replicas }}

  # Server join configuration
  server_join {
    retry_join = [
{{- range $i := intRange .Replicas }}
      "{{ $.ClusterName }}-{{ $i }}.{{ $.HeadlessService }}.{{ $.Namespace }}.svc.cluster.local",
{{- end }}
    ]
    retry_interval = "15s"
    retry_max = 0
  }

  # Gossip encryption
  encrypt = "{{ .GossipKey }}"
}

{{ if .ACLEnabled -}}
# ACL configuration
acl {
  enabled = true
}
{{ end }}

# Autopilot configuration
autopilot {
  cleanup_dead_servers      = {{ .Autopilot.CleanupDeadServers }}
  last_contact_threshold    = "{{ .Autopilot.LastContactThreshold }}"
  max_trailing_logs         = {{ .Autopilot.MaxTrailingLogs }}
  server_stabilization_time = "{{ .Autopilot.ServerStabilizationTime }}"
}

{{ if .TLSEnabled -}}
# TLS configuration
tls {
  http = true
  rpc  = true

  ca_file   = "{{ .TLSCAFile }}"
  cert_file = "{{ .TLSCertFile }}"
  key_file  = "{{ .TLSKeyFile }}"

  verify_server_hostname = {{ .VerifyServerHostname }}
  verify_https_client    = {{ .VerifyHTTPSClient }}
}
{{ end }}

{{ if .AuditEnabled -}}
# Audit logging configuration
audit {
  enabled = true
  sink "file" {
    type               = "file"
    format             = "{{ .AuditFormat }}"
    path               = "/nomad/audit/audit.log"
    delivery_guarantee = "{{ .AuditDeliveryGuarantee }}"
    rotate_duration    = "{{ .AuditRotateDur }}"
    rotate_max_files   = {{ .AuditRotateMax }}
  }
}
{{ end }}

# Telemetry
telemetry {
  publish_allocation_metrics = true
  publish_node_metrics       = true
  prometheus_metrics         = true
}

# Leave on interrupt/term
leave_on_interrupt = true
leave_on_terminate = true

# Disable update check
disable_update_check = true

# Log level
log_level = "INFO"
`
