// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	nomad "github.com/hashicorp/nomad-enterprise-operator/pkg/nomad"
	mock "github.com/stretchr/testify/mock"
)

// MockNomadAPI is an autogenerated mock type for the NomadAPI type
type MockNomadAPI struct {
	mock.Mock
}

type MockNomadAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNomadAPI) EXPECT() *MockNomadAPI_Expecter {
	return &MockNomadAPI_Expecter{mock: &_m.Mock}
}

// AgentSelf provides a mock function with given fields: ctx
func (_m *MockNomadAPI) AgentSelf(ctx context.Context) (*nomad.AgentSelfResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AgentSelf")
	}

	var r0 *nomad.AgentSelfResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*nomad.AgentSelfResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *nomad.AgentSelfResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.AgentSelfResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNomadAPI_AgentSelf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentSelf'
type MockNomadAPI_AgentSelf_Call struct {
	*mock.Call
}

// AgentSelf is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNomadAPI_Expecter) AgentSelf(ctx interface{}) *MockNomadAPI_AgentSelf_Call {
	return &MockNomadAPI_AgentSelf_Call{Call: _e.mock.On("AgentSelf", ctx)}
}

func (_c *MockNomadAPI_AgentSelf_Call) Run(run func(ctx context.Context)) *MockNomadAPI_AgentSelf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockNomadAPI_AgentSelf_Call) Return(_a0 *nomad.AgentSelfResult, _a1 error) *MockNomadAPI_AgentSelf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNomadAPI_AgentSelf_Call) RunAndReturn(run func(context.Context) (*nomad.AgentSelfResult, error)) *MockNomadAPI_AgentSelf_Call {
	_c.Call.Return(run)
	return _c
}

// BootstrapACL provides a mock function with no fields
func (_m *MockNomadAPI) BootstrapACL() (*nomad.ACLBootstrapResult, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BootstrapACL")
	}

	var r0 *nomad.ACLBootstrapResult
	var r1 error
	if rf, ok := ret.Get(0).(func() (*nomad.ACLBootstrapResult, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *nomad.ACLBootstrapResult); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.ACLBootstrapResult)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNomadAPI_BootstrapACL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BootstrapACL'
type MockNomadAPI_BootstrapACL_Call struct {
	*mock.Call
}

// BootstrapACL is a helper method to define mock.On call
func (_e *MockNomadAPI_Expecter) BootstrapACL() *MockNomadAPI_BootstrapACL_Call {
	return &MockNomadAPI_BootstrapACL_Call{Call: _e.mock.On("BootstrapACL")}
}

func (_c *MockNomadAPI_BootstrapACL_Call) Run(run func()) *MockNomadAPI_BootstrapACL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNomadAPI_BootstrapACL_Call) Return(_a0 *nomad.ACLBootstrapResult, _a1 error) *MockNomadAPI_BootstrapACL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNomadAPI_BootstrapACL_Call) RunAndReturn(run func() (*nomad.ACLBootstrapResult, error)) *MockNomadAPI_BootstrapACL_Call {
	_c.Call.Return(run)
	return _c
}

// CheckHealth provides a mock function with no fields
func (_m *MockNomadAPI) CheckHealth() (*nomad.HealthResult, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 *nomad.HealthResult
	var r1 error
	if rf, ok := ret.Get(0).(func() (*nomad.HealthResult, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *nomad.HealthResult); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.HealthResult)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNomadAPI_CheckHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealth'
type MockNomadAPI_CheckHealth_Call struct {
	*mock.Call
}

// CheckHealth is a helper method to define mock.On call
func (_e *MockNomadAPI_Expecter) CheckHealth() *MockNomadAPI_CheckHealth_Call {
	return &MockNomadAPI_CheckHealth_Call{Call: _e.mock.On("CheckHealth")}
}

func (_c *MockNomadAPI_CheckHealth_Call) Run(run func()) *MockNomadAPI_CheckHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNomadAPI_CheckHealth_Call) Return(_a0 *nomad.HealthResult, _a1 error) *MockNomadAPI_CheckHealth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNomadAPI_CheckHealth_Call) RunAndReturn(run func() (*nomad.HealthResult, error)) *MockNomadAPI_CheckHealth_Call {
	_c.Call.Return(run)
	return _c
}

// CreateACLPolicy provides a mock function with given fields: authToken, name, description, rules
func (_m *MockNomadAPI) CreateACLPolicy(authToken string, name string, description string, rules string) error {
	ret := _m.Called(authToken, name, description, rules)

	if len(ret) == 0 {
		panic("no return value specified for CreateACLPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(authToken, name, description, rules)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNomadAPI_CreateACLPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateACLPolicy'
type MockNomadAPI_CreateACLPolicy_Call struct {
	*mock.Call
}

// CreateACLPolicy is a helper method to define mock.On call
//   - authToken string
//   - name string
//   - description string
//   - rules string
func (_e *MockNomadAPI_Expecter) CreateACLPolicy(authToken interface{}, name interface{}, description interface{}, rules interface{}) *MockNomadAPI_CreateACLPolicy_Call {
	return &MockNomadAPI_CreateACLPolicy_Call{Call: _e.mock.On("CreateACLPolicy", authToken, name, description, rules)}
}

func (_c *MockNomadAPI_CreateACLPolicy_Call) Run(run func(authToken string, name string, description string, rules string)) *MockNomadAPI_CreateACLPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockNomadAPI_CreateACLPolicy_Call) Return(_a0 error) *MockNomadAPI_CreateACLPolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNomadAPI_CreateACLPolicy_Call) RunAndReturn(run func(string, string, string, string) error) *MockNomadAPI_CreateACLPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// CreateACLTokenWithPolicies provides a mock function with given fields: authToken, name, policies
func (_m *MockNomadAPI) CreateACLTokenWithPolicies(authToken string, name string, policies []string) (*nomad.ACLTokenResult, error) {
	ret := _m.Called(authToken, name, policies)

	if len(ret) == 0 {
		panic("no return value specified for CreateACLTokenWithPolicies")
	}

	var r0 *nomad.ACLTokenResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, []string) (*nomad.ACLTokenResult, error)); ok {
		return rf(authToken, name, policies)
	}
	if rf, ok := ret.Get(0).(func(string, string, []string) *nomad.ACLTokenResult); ok {
		r0 = rf(authToken, name, policies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.ACLTokenResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, []string) error); ok {
		r1 = rf(authToken, name, policies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNomadAPI_CreateACLTokenWithPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateACLTokenWithPolicies'
type MockNomadAPI_CreateACLTokenWithPolicies_Call struct {
	*mock.Call
}

// CreateACLTokenWithPolicies is a helper method to define mock.On call
//   - authToken string
//   - name string
//   - policies []string
func (_e *MockNomadAPI_Expecter) CreateACLTokenWithPolicies(authToken interface{}, name interface{}, policies interface{}) *MockNomadAPI_CreateACLTokenWithPolicies_Call {
	return &MockNomadAPI_CreateACLTokenWithPolicies_Call{Call: _e.mock.On("CreateACLTokenWithPolicies", authToken, name, policies)}
}

func (_c *MockNomadAPI_CreateACLTokenWithPolicies_Call) Run(run func(authToken string, name string, policies []string)) *MockNomadAPI_CreateACLTokenWithPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockNomadAPI_CreateACLTokenWithPolicies_Call) Return(_a0 *nomad.ACLTokenResult, _a1 error) *MockNomadAPI_CreateACLTokenWithPolicies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNomadAPI_CreateACLTokenWithPolicies_Call) RunAndReturn(run func(string, string, []string) (*nomad.ACLTokenResult, error)) *MockNomadAPI_CreateACLTokenWithPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteACLPolicy provides a mock function with given fields: authToken, name
func (_m *MockNomadAPI) DeleteACLPolicy(authToken string, name string) error {
	ret := _m.Called(authToken, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteACLPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(authToken, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNomadAPI_DeleteACLPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteACLPolicy'
type MockNomadAPI_DeleteACLPolicy_Call struct {
	*mock.Call
}

// DeleteACLPolicy is a helper method to define mock.On call
//   - authToken string
//   - name string
func (_e *MockNomadAPI_Expecter) DeleteACLPolicy(authToken interface{}, name interface{}) *MockNomadAPI_DeleteACLPolicy_Call {
	return &MockNomadAPI_DeleteACLPolicy_Call{Call: _e.mock.On("DeleteACLPolicy", authToken, name)}
}

func (_c *MockNomadAPI_DeleteACLPolicy_Call) Run(run func(authToken string, name string)) *MockNomadAPI_DeleteACLPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockNomadAPI_DeleteACLPolicy_Call) Return(_a0 error) *MockNomadAPI_DeleteACLPolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNomadAPI_DeleteACLPolicy_Call) RunAndReturn(run func(string, string) error) *MockNomadAPI_DeleteACLPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteACLToken provides a mock function with given fields: authToken, accessorID
func (_m *MockNomadAPI) DeleteACLToken(authToken string, accessorID string) error {
	ret := _m.Called(authToken, accessorID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteACLToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(authToken, accessorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNomadAPI_DeleteACLToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteACLToken'
type MockNomadAPI_DeleteACLToken_Call struct {
	*mock.Call
}

// DeleteACLToken is a helper method to define mock.On call
//   - authToken string
//   - accessorID string
func (_e *MockNomadAPI_Expecter) DeleteACLToken(authToken interface{}, accessorID interface{}) *MockNomadAPI_DeleteACLToken_Call {
	return &MockNomadAPI_DeleteACLToken_Call{Call: _e.mock.On("DeleteACLToken", authToken, accessorID)}
}

func (_c *MockNomadAPI_DeleteACLToken_Call) Run(run func(authToken string, accessorID string)) *MockNomadAPI_DeleteACLToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockNomadAPI_DeleteACLToken_Call) Return(_a0 error) *MockNomadAPI_DeleteACLToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNomadAPI_DeleteACLToken_Call) RunAndReturn(run func(string, string) error) *MockNomadAPI_DeleteACLToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetACLToken provides a mock function with given fields: authToken, accessorID
func (_m *MockNomadAPI) GetACLToken(authToken string, accessorID string) (*nomad.ACLTokenResult, error) {
	ret := _m.Called(authToken, accessorID)

	if len(ret) == 0 {
		panic("no return value specified for GetACLToken")
	}

	var r0 *nomad.ACLTokenResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*nomad.ACLTokenResult, error)); ok {
		return rf(authToken, accessorID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *nomad.ACLTokenResult); ok {
		r0 = rf(authToken, accessorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.ACLTokenResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(authToken, accessorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNomadAPI_GetACLToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetACLToken'
type MockNomadAPI_GetACLToken_Call struct {
	*mock.Call
}

// GetACLToken is a helper method to define mock.On call
//   - authToken string
//   - accessorID string
func (_e *MockNomadAPI_Expecter) GetACLToken(authToken interface{}, accessorID interface{}) *MockNomadAPI_GetACLToken_Call {
	return &MockNomadAPI_GetACLToken_Call{Call: _e.mock.On("GetACLToken", authToken, accessorID)}
}

func (_c *MockNomadAPI_GetACLToken_Call) Run(run func(authToken string, accessorID string)) *MockNomadAPI_GetACLToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockNomadAPI_GetACLToken_Call) Return(_a0 *nomad.ACLTokenResult, _a1 error) *MockNomadAPI_GetACLToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNomadAPI_GetACLToken_Call) RunAndReturn(run func(string, string) (*nomad.ACLTokenResult, error)) *MockNomadAPI_GetACLToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAutopilotHealth provides a mock function with given fields: ctx, token
func (_m *MockNomadAPI) GetAutopilotHealth(ctx context.Context, token string) (*nomad.AutopilotHealthResult, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetAutopilotHealth")
	}

	var r0 *nomad.AutopilotHealthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*nomad.AutopilotHealthResult, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *nomad.AutopilotHealthResult); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.AutopilotHealthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNomadAPI_GetAutopilotHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAutopilotHealth'
type MockNomadAPI_GetAutopilotHealth_Call struct {
	*mock.Call
}

// GetAutopilotHealth is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockNomadAPI_Expecter) GetAutopilotHealth(ctx interface{}, token interface{}) *MockNomadAPI_GetAutopilotHealth_Call {
	return &MockNomadAPI_GetAutopilotHealth_Call{Call: _e.mock.On("GetAutopilotHealth", ctx, token)}
}

func (_c *MockNomadAPI_GetAutopilotHealth_Call) Run(run func(ctx context.Context, token string)) *MockNomadAPI_GetAutopilotHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNomadAPI_GetAutopilotHealth_Call) Return(_a0 *nomad.AutopilotHealthResult, _a1 error) *MockNomadAPI_GetAutopilotHealth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNomadAPI_GetAutopilotHealth_Call) RunAndReturn(run func(context.Context, string) (*nomad.AutopilotHealthResult, error)) *MockNomadAPI_GetAutopilotHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeader provides a mock function with no fields
func (_m *MockNomadAPI) GetLeader() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLeader")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNomadAPI_GetLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeader'
type MockNomadAPI_GetLeader_Call struct {
	*mock.Call
}

// GetLeader is a helper method to define mock.On call
func (_e *MockNomadAPI_Expecter) GetLeader() *MockNomadAPI_GetLeader_Call {
	return &MockNomadAPI_GetLeader_Call{Call: _e.mock.On("GetLeader")}
}

func (_c *MockNomadAPI_GetLeader_Call) Run(run func()) *MockNomadAPI_GetLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNomadAPI_GetLeader_Call) Return(_a0 string, _a1 error) *MockNomadAPI_GetLeader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNomadAPI_GetLeader_Call) RunAndReturn(run func() (string, error)) *MockNomadAPI_GetLeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetLicense provides a mock function with given fields: ctx, token
func (_m *MockNomadAPI) GetLicense(ctx context.Context, token string) (*nomad.LicenseResult, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetLicense")
	}

	var r0 *nomad.LicenseResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*nomad.LicenseResult, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *nomad.LicenseResult); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.LicenseResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNomadAPI_GetLicense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLicense'
type MockNomadAPI_GetLicense_Call struct {
	*mock.Call
}

// GetLicense is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockNomadAPI_Expecter) GetLicense(ctx interface{}, token interface{}) *MockNomadAPI_GetLicense_Call {
	return &MockNomadAPI_GetLicense_Call{Call: _e.mock.On("GetLicense", ctx, token)}
}

func (_c *MockNomadAPI_GetLicense_Call) Run(run func(ctx context.Context, token string)) *MockNomadAPI_GetLicense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNomadAPI_GetLicense_Call) Return(_a0 *nomad.LicenseResult, _a1 error) *MockNomadAPI_GetLicense_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNomadAPI_GetLicense_Call) RunAndReturn(run func(context.Context, string) (*nomad.LicenseResult, error)) *MockNomadAPI_GetLicense_Call {
	_c.Call.Return(run)
	return _c
}

// GetPeers provides a mock function with no fields
func (_m *MockNomadAPI) GetPeers() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPeers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNomadAPI_GetPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPeers'
type MockNomadAPI_GetPeers_Call struct {
	*mock.Call
}

// GetPeers is a helper method to define mock.On call
func (_e *MockNomadAPI_Expecter) GetPeers() *MockNomadAPI_GetPeers_Call {
	return &MockNomadAPI_GetPeers_Call{Call: _e.mock.On("GetPeers")}
}

func (_c *MockNomadAPI_GetPeers_Call) Run(run func()) *MockNomadAPI_GetPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNomadAPI_GetPeers_Call) Return(_a0 []string, _a1 error) *MockNomadAPI_GetPeers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNomadAPI_GetPeers_Call) RunAndReturn(run func() ([]string, error)) *MockNomadAPI_GetPeers_Call {
	_c.Call.Return(run)
	return _c
}

// RaftListPeers provides a mock function with given fields: ctx, token
func (_m *MockNomadAPI) RaftListPeers(ctx context.Context, token string) ([]*nomad.RaftPeer, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RaftListPeers")
	}

	var r0 []*nomad.RaftPeer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*nomad.RaftPeer, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*nomad.RaftPeer); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*nomad.RaftPeer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNomadAPI_RaftListPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RaftListPeers'
type MockNomadAPI_RaftListPeers_Call struct {
	*mock.Call
}

// RaftListPeers is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockNomadAPI_Expecter) RaftListPeers(ctx interface{}, token interface{}) *MockNomadAPI_RaftListPeers_Call {
	return &MockNomadAPI_RaftListPeers_Call{Call: _e.mock.On("RaftListPeers", ctx, token)}
}

func (_c *MockNomadAPI_RaftListPeers_Call) Run(run func(ctx context.Context, token string)) *MockNomadAPI_RaftListPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNomadAPI_RaftListPeers_Call) Return(_a0 []*nomad.RaftPeer, _a1 error) *MockNomadAPI_RaftListPeers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNomadAPI_RaftListPeers_Call) RunAndReturn(run func(context.Context, string) ([]*nomad.RaftPeer, error)) *MockNomadAPI_RaftListPeers_Call {
	_c.Call.Return(run)
	return _c
}

// RaftRemovePeer provides a mock function with given fields: ctx, token, id
func (_m *MockNomadAPI) RaftRemovePeer(ctx context.Context, token string, id string) error {
	ret := _m.Called(ctx, token, id)

	if len(ret) == 0 {
		panic("no return value specified for RaftRemovePeer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNomadAPI_RaftRemovePeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RaftRemovePeer'
type MockNomadAPI_RaftRemovePeer_Call struct {
	*mock.Call
}

// RaftRemovePeer is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - id string
func (_e *MockNomadAPI_Expecter) RaftRemovePeer(ctx interface{}, token interface{}, id interface{}) *MockNomadAPI_RaftRemovePeer_Call {
	return &MockNomadAPI_RaftRemovePeer_Call{Call: _e.mock.On("RaftRemovePeer", ctx, token, id)}
}

func (_c *MockNomadAPI_RaftRemovePeer_Call) Run(run func(ctx context.Context, token string, id string)) *MockNomadAPI_RaftRemovePeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNomadAPI_RaftRemovePeer_Call) Return(_a0 error) *MockNomadAPI_RaftRemovePeer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNomadAPI_RaftRemovePeer_Call) RunAndReturn(run func(context.Context, string, string) error) *MockNomadAPI_RaftRemovePeer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNomadAPI creates a new instance of MockNomadAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNomadAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNomadAPI {
	mock := &MockNomadAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
