// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hashicorp/nomad-enterprise-operator/pkg/nomad"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNomadAPI creates a new instance of MockNomadAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNomadAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNomadAPI {
	mock := &MockNomadAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNomadAPI is an autogenerated mock type for the NomadAPI type
type MockNomadAPI struct {
	mock.Mock
}

type MockNomadAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNomadAPI) EXPECT() *MockNomadAPI_Expecter {
	return &MockNomadAPI_Expecter{mock: &_m.Mock}
}

// AgentSelf provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) AgentSelf(ctx context.Context) (*nomad.AgentSelfResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AgentSelf")
	}

	var r0 *nomad.AgentSelfResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*nomad.AgentSelfResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *nomad.AgentSelfResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.AgentSelfResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNomadAPI_AgentSelf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentSelf'
type MockNomadAPI_AgentSelf_Call struct {
	*mock.Call
}

// AgentSelf is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNomadAPI_Expecter) AgentSelf(ctx interface{}) *MockNomadAPI_AgentSelf_Call {
	return &MockNomadAPI_AgentSelf_Call{Call: _e.mock.On("AgentSelf", ctx)}
}

func (_c *MockNomadAPI_AgentSelf_Call) Run(run func(ctx context.Context)) *MockNomadAPI_AgentSelf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNomadAPI_AgentSelf_Call) Return(agentSelfResult *nomad.AgentSelfResult, err error) *MockNomadAPI_AgentSelf_Call {
	_c.Call.Return(agentSelfResult, err)
	return _c
}

func (_c *MockNomadAPI_AgentSelf_Call) RunAndReturn(run func(ctx context.Context) (*nomad.AgentSelfResult, error)) *MockNomadAPI_AgentSelf_Call {
	_c.Call.Return(run)
	return _c
}

// BootstrapACL provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) BootstrapACL() (*nomad.ACLBootstrapResult, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BootstrapACL")
	}

	var r0 *nomad.ACLBootstrapResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*nomad.ACLBootstrapResult, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *nomad.ACLBootstrapResult); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.ACLBootstrapResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNomadAPI_BootstrapACL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BootstrapACL'
type MockNomadAPI_BootstrapACL_Call struct {
	*mock.Call
}

// BootstrapACL is a helper method to define mock.On call
func (_e *MockNomadAPI_Expecter) BootstrapACL() *MockNomadAPI_BootstrapACL_Call {
	return &MockNomadAPI_BootstrapACL_Call{Call: _e.mock.On("BootstrapACL")}
}

func (_c *MockNomadAPI_BootstrapACL_Call) Run(run func()) *MockNomadAPI_BootstrapACL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNomadAPI_BootstrapACL_Call) Return(aCLBootstrapResult *nomad.ACLBootstrapResult, err error) *MockNomadAPI_BootstrapACL_Call {
	_c.Call.Return(aCLBootstrapResult, err)
	return _c
}

func (_c *MockNomadAPI_BootstrapACL_Call) RunAndReturn(run func() (*nomad.ACLBootstrapResult, error)) *MockNomadAPI_BootstrapACL_Call {
	_c.Call.Return(run)
	return _c
}

// CreateACLPolicy provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) CreateACLPolicy(authToken string, name string, description string, rules string) error {
	ret := _mock.Called(authToken, name, description, rules)

	if len(ret) == 0 {
		panic("no return value specified for CreateACLPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = returnFunc(authToken, name, description, rules)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNomadAPI_CreateACLPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateACLPolicy'
type MockNomadAPI_CreateACLPolicy_Call struct {
	*mock.Call
}

// CreateACLPolicy is a helper method to define mock.On call
//   - authToken string
//   - name string
//   - description string
//   - rules string
func (_e *MockNomadAPI_Expecter) CreateACLPolicy(authToken interface{}, name interface{}, description interface{}, rules interface{}) *MockNomadAPI_CreateACLPolicy_Call {
	return &MockNomadAPI_CreateACLPolicy_Call{Call: _e.mock.On("CreateACLPolicy", authToken, name, description, rules)}
}

func (_c *MockNomadAPI_CreateACLPolicy_Call) Run(run func(authToken string, name string, description string, rules string)) *MockNomadAPI_CreateACLPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNomadAPI_CreateACLPolicy_Call) Return(err error) *MockNomadAPI_CreateACLPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNomadAPI_CreateACLPolicy_Call) RunAndReturn(run func(authToken string, name string, description string, rules string) error) *MockNomadAPI_CreateACLPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// CreateACLTokenWithPolicies provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) CreateACLTokenWithPolicies(authToken string, name string, policies []string) (*nomad.ACLTokenResult, error) {
	ret := _mock.Called(authToken, name, policies)

	if len(ret) == 0 {
		panic("no return value specified for CreateACLTokenWithPolicies")
	}

	var r0 *nomad.ACLTokenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) (*nomad.ACLTokenResult, error)); ok {
		return returnFunc(authToken, name, policies)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) *nomad.ACLTokenResult); ok {
		r0 = returnFunc(authToken, name, policies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.ACLTokenResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, []string) error); ok {
		r1 = returnFunc(authToken, name, policies)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNomadAPI_CreateACLTokenWithPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateACLTokenWithPolicies'
type MockNomadAPI_CreateACLTokenWithPolicies_Call struct {
	*mock.Call
}

// CreateACLTokenWithPolicies is a helper method to define mock.On call
//   - authToken string
//   - name string
//   - policies []string
func (_e *MockNomadAPI_Expecter) CreateACLTokenWithPolicies(authToken interface{}, name interface{}, policies interface{}) *MockNomadAPI_CreateACLTokenWithPolicies_Call {
	return &MockNomadAPI_CreateACLTokenWithPolicies_Call{Call: _e.mock.On("CreateACLTokenWithPolicies", authToken, name, policies)}
}

func (_c *MockNomadAPI_CreateACLTokenWithPolicies_Call) Run(run func(authToken string, name string, policies []string)) *MockNomadAPI_CreateACLTokenWithPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNomadAPI_CreateACLTokenWithPolicies_Call) Return(aCLTokenResult *nomad.ACLTokenResult, err error) *MockNomadAPI_CreateACLTokenWithPolicies_Call {
	_c.Call.Return(aCLTokenResult, err)
	return _c
}

func (_c *MockNomadAPI_CreateACLTokenWithPolicies_Call) RunAndReturn(run func(authToken string, name string, policies []string) (*nomad.ACLTokenResult, error)) *MockNomadAPI_CreateACLTokenWithPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// CreateManagementACLToken provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) CreateManagementACLToken(authToken string, name string) (*nomad.ACLTokenResult, error) {
	ret := _mock.Called(authToken, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateManagementACLToken")
	}

	var r0 *nomad.ACLTokenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*nomad.ACLTokenResult, error)); ok {
		return returnFunc(authToken, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *nomad.ACLTokenResult); ok {
		r0 = returnFunc(authToken, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.ACLTokenResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(authToken, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNomadAPI_CreateManagementACLToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateManagementACLToken'
type MockNomadAPI_CreateManagementACLToken_Call struct {
	*mock.Call
}

// CreateManagementACLToken is a helper method to define mock.On call
//   - authToken string
//   - name string
func (_e *MockNomadAPI_Expecter) CreateManagementACLToken(authToken interface{}, name interface{}) *MockNomadAPI_CreateManagementACLToken_Call {
	return &MockNomadAPI_CreateManagementACLToken_Call{Call: _e.mock.On("CreateManagementACLToken", authToken, name)}
}

func (_c *MockNomadAPI_CreateManagementACLToken_Call) Run(run func(authToken string, name string)) *MockNomadAPI_CreateManagementACLToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNomadAPI_CreateManagementACLToken_Call) Return(aCLTokenResult *nomad.ACLTokenResult, err error) *MockNomadAPI_CreateManagementACLToken_Call {
	_c.Call.Return(aCLTokenResult, err)
	return _c
}

func (_c *MockNomadAPI_CreateManagementACLToken_Call) RunAndReturn(run func(authToken string, name string) (*nomad.ACLTokenResult, error)) *MockNomadAPI_CreateManagementACLToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteACLPolicy provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) DeleteACLPolicy(authToken string, name string) error {
	ret := _mock.Called(authToken, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteACLPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(authToken, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNomadAPI_DeleteACLPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteACLPolicy'
type MockNomadAPI_DeleteACLPolicy_Call struct {
	*mock.Call
}

// DeleteACLPolicy is a helper method to define mock.On call
//   - authToken string
//   - name string
func (_e *MockNomadAPI_Expecter) DeleteACLPolicy(authToken interface{}, name interface{}) *MockNomadAPI_DeleteACLPolicy_Call {
	return &MockNomadAPI_DeleteACLPolicy_Call{Call: _e.mock.On("DeleteACLPolicy", authToken, name)}
}

func (_c *MockNomadAPI_DeleteACLPolicy_Call) Run(run func(authToken string, name string)) *MockNomadAPI_DeleteACLPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNomadAPI_DeleteACLPolicy_Call) Return(err error) *MockNomadAPI_DeleteACLPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNomadAPI_DeleteACLPolicy_Call) RunAndReturn(run func(authToken string, name string) error) *MockNomadAPI_DeleteACLPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteACLToken provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) DeleteACLToken(authToken string, accessorID string) error {
	ret := _mock.Called(authToken, accessorID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteACLToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(authToken, accessorID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNomadAPI_DeleteACLToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteACLToken'
type MockNomadAPI_DeleteACLToken_Call struct {
	*mock.Call
}

// DeleteACLToken is a helper method to define mock.On call
//   - authToken string
//   - accessorID string
func (_e *MockNomadAPI_Expecter) DeleteACLToken(authToken interface{}, accessorID interface{}) *MockNomadAPI_DeleteACLToken_Call {
	return &MockNomadAPI_DeleteACLToken_Call{Call: _e.mock.On("DeleteACLToken", authToken, accessorID)}
}

func (_c *MockNomadAPI_DeleteACLToken_Call) Run(run func(authToken string, accessorID string)) *MockNomadAPI_DeleteACLToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNomadAPI_DeleteACLToken_Call) Return(err error) *MockNomadAPI_DeleteACLToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNomadAPI_DeleteACLToken_Call) RunAndReturn(run func(authToken string, accessorID string) error) *MockNomadAPI_DeleteACLToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetACLPolicy provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) GetACLPolicy(authToken string, name string) (*nomad.ACLPolicyResult, error) {
	ret := _mock.Called(authToken, name)

	if len(ret) == 0 {
		panic("no return value specified for GetACLPolicy")
	}

	var r0 *nomad.ACLPolicyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*nomad.ACLPolicyResult, error)); ok {
		return returnFunc(authToken, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *nomad.ACLPolicyResult); ok {
		r0 = returnFunc(authToken, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.ACLPolicyResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(authToken, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNomadAPI_GetACLPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetACLPolicy'
type MockNomadAPI_GetACLPolicy_Call struct {
	*mock.Call
}

// GetACLPolicy is a helper method to define mock.On call
//   - authToken string
//   - name string
func (_e *MockNomadAPI_Expecter) GetACLPolicy(authToken interface{}, name interface{}) *MockNomadAPI_GetACLPolicy_Call {
	return &MockNomadAPI_GetACLPolicy_Call{Call: _e.mock.On("GetACLPolicy", authToken, name)}
}

func (_c *MockNomadAPI_GetACLPolicy_Call) Run(run func(authToken string, name string)) *MockNomadAPI_GetACLPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNomadAPI_GetACLPolicy_Call) Return(aCLPolicyResult *nomad.ACLPolicyResult, err error) *MockNomadAPI_GetACLPolicy_Call {
	_c.Call.Return(aCLPolicyResult, err)
	return _c
}

func (_c *MockNomadAPI_GetACLPolicy_Call) RunAndReturn(run func(authToken string, name string) (*nomad.ACLPolicyResult, error)) *MockNomadAPI_GetACLPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetACLToken provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) GetACLToken(authToken string, accessorID string) (*nomad.ACLTokenResult, error) {
	ret := _mock.Called(authToken, accessorID)

	if len(ret) == 0 {
		panic("no return value specified for GetACLToken")
	}

	var r0 *nomad.ACLTokenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*nomad.ACLTokenResult, error)); ok {
		return returnFunc(authToken, accessorID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *nomad.ACLTokenResult); ok {
		r0 = returnFunc(authToken, accessorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.ACLTokenResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(authToken, accessorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNomadAPI_GetACLToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetACLToken'
type MockNomadAPI_GetACLToken_Call struct {
	*mock.Call
}

// GetACLToken is a helper method to define mock.On call
//   - authToken string
//   - accessorID string
func (_e *MockNomadAPI_Expecter) GetACLToken(authToken interface{}, accessorID interface{}) *MockNomadAPI_GetACLToken_Call {
	return &MockNomadAPI_GetACLToken_Call{Call: _e.mock.On("GetACLToken", authToken, accessorID)}
}

func (_c *MockNomadAPI_GetACLToken_Call) Run(run func(authToken string, accessorID string)) *MockNomadAPI_GetACLToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNomadAPI_GetACLToken_Call) Return(aCLTokenResult *nomad.ACLTokenResult, err error) *MockNomadAPI_GetACLToken_Call {
	_c.Call.Return(aCLTokenResult, err)
	return _c
}

func (_c *MockNomadAPI_GetACLToken_Call) RunAndReturn(run func(authToken string, accessorID string) (*nomad.ACLTokenResult, error)) *MockNomadAPI_GetACLToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAutopilotHealth provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) GetAutopilotHealth(ctx context.Context, token string) (*nomad.AutopilotHealthResult, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetAutopilotHealth")
	}

	var r0 *nomad.AutopilotHealthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*nomad.AutopilotHealthResult, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *nomad.AutopilotHealthResult); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.AutopilotHealthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNomadAPI_GetAutopilotHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAutopilotHealth'
type MockNomadAPI_GetAutopilotHealth_Call struct {
	*mock.Call
}

// GetAutopilotHealth is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockNomadAPI_Expecter) GetAutopilotHealth(ctx interface{}, token interface{}) *MockNomadAPI_GetAutopilotHealth_Call {
	return &MockNomadAPI_GetAutopilotHealth_Call{Call: _e.mock.On("GetAutopilotHealth", ctx, token)}
}

func (_c *MockNomadAPI_GetAutopilotHealth_Call) Run(run func(ctx context.Context, token string)) *MockNomadAPI_GetAutopilotHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNomadAPI_GetAutopilotHealth_Call) Return(autopilotHealthResult *nomad.AutopilotHealthResult, err error) *MockNomadAPI_GetAutopilotHealth_Call {
	_c.Call.Return(autopilotHealthResult, err)
	return _c
}

func (_c *MockNomadAPI_GetAutopilotHealth_Call) RunAndReturn(run func(ctx context.Context, token string) (*nomad.AutopilotHealthResult, error)) *MockNomadAPI_GetAutopilotHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeader provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) GetLeader() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLeader")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNomadAPI_GetLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeader'
type MockNomadAPI_GetLeader_Call struct {
	*mock.Call
}

// GetLeader is a helper method to define mock.On call
func (_e *MockNomadAPI_Expecter) GetLeader() *MockNomadAPI_GetLeader_Call {
	return &MockNomadAPI_GetLeader_Call{Call: _e.mock.On("GetLeader")}
}

func (_c *MockNomadAPI_GetLeader_Call) Run(run func()) *MockNomadAPI_GetLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNomadAPI_GetLeader_Call) Return(s string, err error) *MockNomadAPI_GetLeader_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockNomadAPI_GetLeader_Call) RunAndReturn(run func() (string, error)) *MockNomadAPI_GetLeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetLicense provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) GetLicense(ctx context.Context, token string) (*nomad.LicenseResult, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetLicense")
	}

	var r0 *nomad.LicenseResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*nomad.LicenseResult, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *nomad.LicenseResult); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nomad.LicenseResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNomadAPI_GetLicense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLicense'
type MockNomadAPI_GetLicense_Call struct {
	*mock.Call
}

// GetLicense is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockNomadAPI_Expecter) GetLicense(ctx interface{}, token interface{}) *MockNomadAPI_GetLicense_Call {
	return &MockNomadAPI_GetLicense_Call{Call: _e.mock.On("GetLicense", ctx, token)}
}

func (_c *MockNomadAPI_GetLicense_Call) Run(run func(ctx context.Context, token string)) *MockNomadAPI_GetLicense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNomadAPI_GetLicense_Call) Return(licenseResult *nomad.LicenseResult, err error) *MockNomadAPI_GetLicense_Call {
	_c.Call.Return(licenseResult, err)
	return _c
}

func (_c *MockNomadAPI_GetLicense_Call) RunAndReturn(run func(ctx context.Context, token string) (*nomad.LicenseResult, error)) *MockNomadAPI_GetLicense_Call {
	_c.Call.Return(run)
	return _c
}

// KeyringDelete provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) KeyringDelete(ctx context.Context, token string, keyID string) error {
	ret := _mock.Called(ctx, token, keyID)

	if len(ret) == 0 {
		panic("no return value specified for KeyringDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, token, keyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNomadAPI_KeyringDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyringDelete'
type MockNomadAPI_KeyringDelete_Call struct {
	*mock.Call
}

// KeyringDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - keyID string
func (_e *MockNomadAPI_Expecter) KeyringDelete(ctx interface{}, token interface{}, keyID interface{}) *MockNomadAPI_KeyringDelete_Call {
	return &MockNomadAPI_KeyringDelete_Call{Call: _e.mock.On("KeyringDelete", ctx, token, keyID)}
}

func (_c *MockNomadAPI_KeyringDelete_Call) Run(run func(ctx context.Context, token string, keyID string)) *MockNomadAPI_KeyringDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNomadAPI_KeyringDelete_Call) Return(err error) *MockNomadAPI_KeyringDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNomadAPI_KeyringDelete_Call) RunAndReturn(run func(ctx context.Context, token string, keyID string) error) *MockNomadAPI_KeyringDelete_Call {
	_c.Call.Return(run)
	return _c
}

// KeyringList provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) KeyringList(ctx context.Context, token string) ([]*nomad.RootKey, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for KeyringList")
	}

	var r0 []*nomad.RootKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*nomad.RootKey, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*nomad.RootKey); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*nomad.RootKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNomadAPI_KeyringList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyringList'
type MockNomadAPI_KeyringList_Call struct {
	*mock.Call
}

// KeyringList is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockNomadAPI_Expecter) KeyringList(ctx interface{}, token interface{}) *MockNomadAPI_KeyringList_Call {
	return &MockNomadAPI_KeyringList_Call{Call: _e.mock.On("KeyringList", ctx, token)}
}

func (_c *MockNomadAPI_KeyringList_Call) Run(run func(ctx context.Context, token string)) *MockNomadAPI_KeyringList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNomadAPI_KeyringList_Call) Return(rootKeys []*nomad.RootKey, err error) *MockNomadAPI_KeyringList_Call {
	_c.Call.Return(rootKeys, err)
	return _c
}

func (_c *MockNomadAPI_KeyringList_Call) RunAndReturn(run func(ctx context.Context, token string) ([]*nomad.RootKey, error)) *MockNomadAPI_KeyringList_Call {
	_c.Call.Return(run)
	return _c
}

// KeyringRotateFull provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) KeyringRotateFull(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for KeyringRotateFull")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNomadAPI_KeyringRotateFull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyringRotateFull'
type MockNomadAPI_KeyringRotateFull_Call struct {
	*mock.Call
}

// KeyringRotateFull is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockNomadAPI_Expecter) KeyringRotateFull(ctx interface{}, token interface{}) *MockNomadAPI_KeyringRotateFull_Call {
	return &MockNomadAPI_KeyringRotateFull_Call{Call: _e.mock.On("KeyringRotateFull", ctx, token)}
}

func (_c *MockNomadAPI_KeyringRotateFull_Call) Run(run func(ctx context.Context, token string)) *MockNomadAPI_KeyringRotateFull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNomadAPI_KeyringRotateFull_Call) Return(err error) *MockNomadAPI_KeyringRotateFull_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNomadAPI_KeyringRotateFull_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockNomadAPI_KeyringRotateFull_Call {
	_c.Call.Return(run)
	return _c
}

// RaftListPeers provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) RaftListPeers(ctx context.Context, token string) ([]*nomad.RaftPeer, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RaftListPeers")
	}

	var r0 []*nomad.RaftPeer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*nomad.RaftPeer, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*nomad.RaftPeer); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*nomad.RaftPeer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNomadAPI_RaftListPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RaftListPeers'
type MockNomadAPI_RaftListPeers_Call struct {
	*mock.Call
}

// RaftListPeers is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockNomadAPI_Expecter) RaftListPeers(ctx interface{}, token interface{}) *MockNomadAPI_RaftListPeers_Call {
	return &MockNomadAPI_RaftListPeers_Call{Call: _e.mock.On("RaftListPeers", ctx, token)}
}

func (_c *MockNomadAPI_RaftListPeers_Call) Run(run func(ctx context.Context, token string)) *MockNomadAPI_RaftListPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNomadAPI_RaftListPeers_Call) Return(raftPeers []*nomad.RaftPeer, err error) *MockNomadAPI_RaftListPeers_Call {
	_c.Call.Return(raftPeers, err)
	return _c
}

func (_c *MockNomadAPI_RaftListPeers_Call) RunAndReturn(run func(ctx context.Context, token string) ([]*nomad.RaftPeer, error)) *MockNomadAPI_RaftListPeers_Call {
	_c.Call.Return(run)
	return _c
}

// RaftRemovePeer provides a mock function for the type MockNomadAPI
func (_mock *MockNomadAPI) RaftRemovePeer(ctx context.Context, token string, id string) error {
	ret := _mock.Called(ctx, token, id)

	if len(ret) == 0 {
		panic("no return value specified for RaftRemovePeer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, token, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNomadAPI_RaftRemovePeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RaftRemovePeer'
type MockNomadAPI_RaftRemovePeer_Call struct {
	*mock.Call
}

// RaftRemovePeer is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - id string
func (_e *MockNomadAPI_Expecter) RaftRemovePeer(ctx interface{}, token interface{}, id interface{}) *MockNomadAPI_RaftRemovePeer_Call {
	return &MockNomadAPI_RaftRemovePeer_Call{Call: _e.mock.On("RaftRemovePeer", ctx, token, id)}
}

func (_c *MockNomadAPI_RaftRemovePeer_Call) Run(run func(ctx context.Context, token string, id string)) *MockNomadAPI_RaftRemovePeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNomadAPI_RaftRemovePeer_Call) Return(err error) *MockNomadAPI_RaftRemovePeer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNomadAPI_RaftRemovePeer_Call) RunAndReturn(run func(ctx context.Context, token string, id string) error) *MockNomadAPI_RaftRemovePeer_Call {
	_c.Call.Return(run)
	return _c
}
